### ISSUE TITLE
model plots

### ISSUE THREAD

**Issue by SteveGoldstein** [MarlinRLee/Covid-Waste-Water-Exploration#1]
1.  MMSD should not be included in the model with the five interceptors because doing so would use redundant information.
2. The panels need labels (e.g. P02).
3. What's is the grey area around the smoothed model curve?  Is it a confidence interval from the model output object?
4. In addition to this view with the time-shifted rolling average of positivity, let's have a version with the original (non-shifted).  I think that might be easier for our target audience to interpret quickly.  They could then, by eye, do the time-shifting.
5. Let's have the R^2 values somewhere on this plot (maybe in a text box in corner or simply a table or text elsewhere that I could cut and paste into a pptx slide.

After these tweaks, this should be a really good vehicle for our presentation.  Thanks!!

**Comment by MarlinRLee** [comment]
1) Resolved
2)Resolved
3)It is the confidence interval. I found it helpful to communicate where there is a lack of data.
4)Would you want it graphed on the same graph or just a separate version of the document which shows the unshifted results.
5)Resolved
